[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "smartpi-gpio"
version = "1.0.0"
description = "A GPIO library for Smart Pi"
authors = ["ADNroboticsfr <adnroboticsfr@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.scripts]
gpio = "gpio.scripts:main"
