[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "smart-pi-gpio"
version = "1.0.0"
description = "A GPIO library for Smart Pi"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
# Add your development dependencies here

[tool.poetry.scripts]
gpio-smpi = "gpio.scripts:main"
